export const SKILLS = {
  "Backend": ["Java", "Spring Boot", "Spring","Python", "C", "REST APIs", "FastAPI", "Flask"],
  "AI & Machine Learning": ["TensorFlow", "PyTorch", "scikit-learn", "GenAI", "NLP", "Computer Vision"],
  "Databases": ["DynamoDB", "PostgreSQL", "MongoDB", "Redis", "MySQL", "Firebase"],
  "DevOps & Cloud": ["Docker", "Kubernetes", "AWS", "Google Cloud", "CI/CD"],
  "Frontend": ["React", "Next.js", "TypeScript", "Tailwind CSS"],
  "Monitoring & Logging": ["Splunk", "Sumo Logic", "Telemetry-Kibana"],
  "Soft Skills": ["Problem Solving", "Team Collaboration", "Agile Methodologies", "Effective Communication", "Mentoring", "Leadership", "Scrum", "Kanban"],
};

export const PROJECTS = [
  {
    id: "proj-5",
    title: "Adversarial Attack and Defense Analysis ",
    summary: "Implemented diffusion based Generative AI adversarial attacks on images and through loss function optimization by modifying cross-entropy loss to Carlini & Wagner loss, improving the attack transferability by 39%. Researched about various image immunization techniques including PhotoGuard, AdvPaint, and DiffusionGuard, evaluated PhotoGuard on a small subset of images, achieving a success rate of 96.67% in preventing attacks",
    tags: ["Stable Diffusion", "PyTorch", "Computer Vision", "Python", "Machine Learning", "Generative AI", "AI Security", "Adversarial Attacks", "AI Defense"],
    repoUrl: "https://github.com/gavingleinig/semantic-transformation-adv-attack/tree/vijay",
    liveUrl: null,
    imageId: "project-5",
  },
  {
    id: "proj-7",
    title: "Visual SketchPad Implementation and Benchmarking ",
    summary: "Evaluated a visual chain-of-thought framework on the Path-VQA dataset containing 6k+ pathology Q&A pairs, focusing on yes/no accuracy and qualitative reasoning quality. Benchmarked GPT-4o, GPT-3.5-mini, Gemini-2.5-Flash, and BLIP-VQA models on medical visual reasoning, analyzing performance gaps and model strengths across tasks and reported a 10% improvement over baseline reasoning performance",
    tags: ["Visual Chain-of-Thought", "Gemini-2.5-Flash", "GPT-4o", "Path-VQA Dataset", "Medical Visual Reasoning", "Computer Vision"],
    repoUrl: "https://github.com/vijay-murugan/Visual-Chain-of-Thought",
    liveUrl: null,
    imageId: "project-7",
  },
  {
    id: "proj-4",
    title: "Automated Shopping Cart",
    summary: "Engineered an ML-based Android + IoT system for grocery classification and weight detection, achieving 95%+ accuracy, 98% precision, and 90%+ real-world accuracy using custom datasets and ensemble models (EfficientNetV2, MobileNetV2)\n"
    + " Published findings at ICSMDI 2023 and secured an Indian Patent (#555691), showcasing the application of ML research to practical retail challenges by reducing checkout wait times and enabling scalable deployment",
    tags: ["TensorFlow", "Flask", "Computer Vision", "Image Recognition", "Android", "IoT", "Java", "Python"],
    repoUrl: "https://github.com/vijay-murugan/automated-shopping-cart",
    liveUrl: null,
    imageId: "project-4",
  },
  {
    id: "proj-6",
    title: "CLIP Model Optimization ",
    summary: "Optimized self-supervised CLIP training by testing against multiple optimizers including Adam, AdamP, and AdamW and various loss functions SogCLR and iSogCLR achieving best zero-shot top 1 accuracy of 24.45% using AdamW with SogCLR loss. Added Weights & Bias for checkpoint management to reduce the training time by 87%",
    tags: ["CLIP", "PyTorch", "Computer Vision", "Python", "Machine Learning", "AdamW Optimizer", "Self-Supervised Learning"],
    repoUrl: "",
    liveUrl: null,
    imageId: "project-6",
  },
  {
    id: "proj-8",
    title: "Bill Splitter App ",
    summary: "Engineered a full-stack bill splitting application using FastAPI, React, and MongoDB, building 12+ API endpoints and 8+ interactive UI components for multi-user expense management, processing split transactions with automated balance tracking",
    tags: ["FastAPI", "Python", "React", "MongoDB", "JavaScript", "Full-Stack Development"],
    repoUrl: "https://github.com/vijay-murugan/bill-split",
    liveUrl: null,
    imageId: "project-8x",
  },
  {
    id: "proj-1",
    title: "Company Logo Search & Flowchart Builder ",
    summary: "Engineered a scalable React.js application with Firebase authentication serving 250+ users at 99% reliability, integrating Google Favicon API, MongoDB storage, and canvas-based development tools to build flow-charts with company logos.",
    tags: ["React", "MongoDB", "NGINX", "Firebase"],
    repoUrl: "https://github.com/vijay-murugan/logolego",
    liveUrl: null,
  },
  {
    id: "proj-2",
    title: "Smart Movie Recommendation",
    summary: "Built a personalized movie recommendation system by training a hybrid ML model combining K-means and cosine similarity. Deployed with Fast API backend, TypeScript frontend, and Firebase authentication to deliver over 90% accurate suggestions.",
    tags: ["Python", "Fast API", "ML", "TypeScript", "Firebase"],
    repoUrl: "https://github.com/vijay-murugan/movie-recommendation",
    liveUrl: null,
    imageId: "project-2",
  },
  {
    id: "proj-3",
    title: "Intelligent PDF Content Enhancer",
    summary: "Developed an intelligent PDF content enhancer using advanced NLP techniques to automatically summarize and extract key information from documents. Integrated with a user-friendly interface built on React and FastAPI.",
    tags: ["Google Gemini LLM", "Fast API", "ML", "TypeScript", "React", "Vite"],
    repoUrl: "https://github.com/vijay-murugan/movie-recommendation",
    liveUrl: null,
    imageId: "project-2",
  },
];
